name: my_portfolio_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  cupertino_icons: ^1.0.2
  dynamic_icon_flutter: ^0.0.7
  flutter_vector_icons: ^2.0.0
  url_launcher: ^6.1.11
  intl: ^0.18.1
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_hooks: ^0.18.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/